# Generated by Django 4.1.13 on 2024-07-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_profile_remove_student_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Lifelong learner interested in empowering other curious developers'),
            preserve_default=False,
        ),
    ]
