# Generated by Django 4.1.13 on 2024-08-01 01:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_alter_profile_saved_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
